version: '3'
services:
  web:
    image: loldesign-telzir-web-challenge
    build:
      context: ./react-ui
      target: production
      args:
        REACT_APP_API_URL: http://localhost:9000/api/v1
    ports:
      - "8080:80"
