version: '3'
services:
  web:
    container_name: telzir_web
    build:
      context: ./react-ui
      target: development
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000/api/v1
    stdin_open: true
    volumes:
       - ./react-ui:/usr/src/app
       - /usr/src/app/node_modules
