
name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
env:
  IMAGE_NAME: loldesign-telzir-web-challenge
  REGISTRY_NAME: fonsecabarreto

jobs:
  pushToDockerHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose -f docker-compose.build.yml build --no-cache web 
      - run: docker tag $IMAGE_NAME $REGISTRY_NAME/$IMAGE_NAME
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push $REGISTRY_NAME/$IMAGE_NAME:latest